#!/bin/sh
cd /var/workdir

cp -r /var/src/* /var/workdir

sed -i "s/XXX/${VERSION}/" expath-pkg.xml >> expath-pkg.xml

ant xar

if [ $? -ne 0 ]
then
    echo "could not build"
    exit 1
fi

cp build/* /var/dst
