#!/bin/sh
cd /var/workdir

cp -r /var/src/* /var/workdir

sed -i "s/XXX/${VERSION}/" expath-pkg.xml >> expath-pkg.xml

if [ $MINIMAL -eq 1 ]
then
    # test data build
    ant mini
else
    # normal build
    ant xar
fi

if [ $? -ne 0 ]
then
    echo "could not build"
    exit 1
fi

cp build/* /var/dst

ls /var/dst
