FROM frekele/ant

MAINTAINER Helmut Konrad Schewe <helmutus@outlook.com>

ENV PACKAGE=NO_PACKAGE
ENV VERSION=NO_VERSION

VOLUME /var/src
VOLUME /var/workdir
VOLUME /var/dst

COPY buildit /var/buildit

WORKDIR /var/workdir

ENTRYPOINT /var/buildit
